clone_folder: "c:\\WORK"

environment:
  global:
    CABOPTS:  "--http-transport=plain-http"
  matrix:
    # 64 bit builds
    - GHCVER: "head"
      CHOCOPTS: --pre

install:
 - "choco source add -n mistuke -s https://www.myget.org/F/mistuke/api/v2"
 - "choco install -y cabal-head -pre %CHOCOPTS%"
 - "IF '%GHCVER%'=='head' choco install -vy ghc-head %CHOCOPTS%"
 - "IF NOT '%GHCVER%'=='head' choco install -vy ghc --version %GHCVER% %CHOCOPTS%"
 - "refreshenv"
 - "set PATH=C:\\ghc\\ghc-%GHCVER%:C:\\msys64\\mingw64\\bin;C:\\msys64\\usr\\bin;%PATH%"
 - "cabal --version"
 - "ghc --version"
 - "cabal %CABOPTS% update -v"

build: off

test_script:
 - IF EXIST configure.ac bash -c "autoreconf -i"
 - "echo packages:. > cabal.project"
 - "cabal %CABOPTS% new-build -j1 all"
